### ISSUE TITLE
can sample json file be provided

### ISSUE THREAD

**Issue by sushmithajram13** [JFFail/GroovyJWT#1]
In the code, there is a json file where appsecreta and other details are picked up . Cant find the same in the code. Can it be provided?

**Comment by jfabry-noc** [comment]
I just added a [sample headers.json file](https://github.com/jfabry-noc/GroovyJWT/commit/2fd4125b8f18321bae3dab2a8e30acb8937a9465) in the last commit. Just be aware that these values could change based on what is required by the platform you're authenticating against, though in that case you should just need to add or remove the appropriate items from your own JSON file.
